### ISSUE TITLE
Selecting Hex above 2GB

### ISSUE THREAD

**Issue by pjrinaldi** [Simsys/qhexedit2#104]
When loading a large file, such as 14GB, after the 2GB mark, I cannot select hex code to save. I can select hex before the 2GB mark, and its the 0x80000000 or 2,147,483,648.  I was able to reproduce this with the example editor.

Thanks.

**Comment by Simsys** [comment]
fixed, see fb1c2bc61918690616f0ab0213e6d1392cc115d6

**Comment by pjrinaldi** [comment]
Thank you so much for taking care of this. It ended up being such a small
code change, I felt bad that I didn't look into it first and figure it out.

I haven't worked on other people's projects through github before, but I
wanted to see if you wanted to me to submit additions I added for
functionality I needed that might be useful to your code as well.
-------
(qhexedit.h header file)

// Enables the selected content to be exported as binary to a file for
further review.
QByteArray selectionToByteArray();

 // Enable displaying the selection length. (signal)
    void selectionChanged();

(qhexedit.cpp source file)
// Enables selection to be carved to a binary file for further review.
QByteArray QHexEdit::selectionToByteArray()
{
    QByteArray ba = _chunks->data(getSelectionBegin(), getSelectionEnd() -
getSelectionBegin());
    return ba;
}

I also modified the QHexEdit::mousePressEvent(..)
    if(event->buttons() == Qt::LeftButton) // ensures a right click context
menu will open and the below only occurs for left mouse click
    {
        _blink = false;
        viewport()->update();
        qint64 cPos = cursorPosition(event->pos());
        if (cPos >= 0)
        {
            resetSelection(cPos);
            setCursorPosition(cPos);
        }
    }

I am writing a GUI forensic tool for linux, "pjrinaldi/wombatforensics" and
am using your editor as the main image file viewer and as the individual
selected file content viewer. I added "carving" selections to a file by
adding the save binary data, rather than the ascii data. I added the
selectionChanged() signal, so I could update the length of selected text. I
also modified the mousePressEvent by adding the "Left Mouse Button" if
statement so I could open a context menu to choose to carve the selected
text to a file, or other operations not implemented yet.

I also added background color highlighting for file contents in the main
editor, so It will show the file contents as "light blue background" and
the file slack as a "light red background". I don't think this feature is
very useful for your default hex editor, but I can provide if it you want.

Let me know if you want me to figure out how to send the above changes to
your code. Again, I can't thank you enough for your qhexedit code.

Pasquale

**Comment by Simsys** [comment]
Hi Pasquale,

the "Selecting Hex above 2GB" was a hard error. Thank you for reporting
this bug.

I'm always happy about pull requests. However, it makes sense to exchange
information about API changes beforehand.
- selectionToByteArray(): good Idea, please provide pull request
- selectionChanged(): good Idea, please provide pull request
- modifying mousePressEvent(): good Idea, please provide pull request

I haven't quite understood the feature with the different background colors
yet.

Please open an issue for each feature idea in the future. This is easier to
handle. Create pull requests in a way that a pull request really contains
only one feature. This feature should be complete: code changes, adaptation
of documentation, SIP file for Python bindings etc. For the above changes
you would create three pull requests.

cheers
Winfried

Am So., 24. März 2019 um 16:10 Uhr schrieb pjrinaldi <
notifications@github.com>:

> Thank you so much for taking care of this. It ended up being such a small
> code change, I felt bad that I didn't look into it first and figure it out.
>
> I haven't worked on other people's projects through github before, but I
> wanted to see if you wanted to me to submit additions I added for
> functionality I needed that might be useful to your code as well.
> -------
> (qhexedit.h header file)
>
> // Enables the selected content to be exported as binary to a file for
> further review.
> QByteArray selectionToByteArray();
>
> // Enable displaying the selection length. (signal)
> void selectionChanged();
>
> (qhexedit.cpp source file)
> // Enables selection to be carved to a binary file for further review.
> QByteArray QHexEdit::selectionToByteArray()
> {
> QByteArray ba = _chunks->data(getSelectionBegin(), getSelectionEnd() -
> getSelectionBegin());
> return ba;
> }
>
> I also modified the QHexEdit::mousePressEvent(..)
> if(event->buttons() == Qt::LeftButton) // ensures a right click context
> menu will open and the below only occurs for left mouse click
> {
> _blink = false;
> viewport()->update();
> qint64 cPos = cursorPosition(event->pos());
> if (cPos >= 0)
> {
> resetSelection(cPos);
> setCursorPosition(cPos);
> }
> }
>
> I am writing a GUI forensic tool for linux, "pjrinaldi/wombatforensics" and
> am using your editor as the main image file viewer and as the individual
> selected file content viewer. I added "carving" selections to a file by
> adding the save binary data, rather than the ascii data. I added the
> selectionChanged() signal, so I could update the length of selected text. I
> also modified the mousePressEvent by adding the "Left Mouse Button" if
> statement so I could open a context menu to choose to carve the selected
> text to a file, or other operations not implemented yet.
>
> I also added background color highlighting for file contents in the main
> editor, so It will show the file contents as "light blue background" and
> the file slack as a "light red background". I don't think this feature is
> very useful for your default hex editor, but I can provide if it you want.
>
> Let me know if you want me to figure out how to send the above changes to
> your code. Again, I can't thank you enough for your qhexedit code.
>
> Pasquale
>
