### ISSUE TITLE
Clarify Package Distribution/Install 

### ISSUE THREAD

**Issue by scottfurry** [Simsys/qhexedit2#113]
The README informs readers that "QHexEdit is a hex editor widget". However, some Linux distributions ( traced through [qhexedit2 repology project entry](https://repology.org/project/qhexedit2/versions) ) create/install a desktop file for the "example program".

If I understand intent properly, focus of repository is the Qt addon widget ability, not a standalone application. However, other Linux distro's do install the "example" program as a stand-alone application into default location (usually `/usr/bin`).

The minor annoyance I'm trying to grapple with is what icon to use. The "example" uses an `.ico` file, and QT is content with using that for the application icon. Linux desktops don't use MS `.ico` format images for menu entries. There is no other single icon for the example program. openSuse, for example, takes the `docs/html/phexedit.png` image, scales it w/ imagemagick, and uses that as the icon for the menu entry when installing the example program( see [spec file](https://build.opensuse.org/package/view_file/openSUSE:Factory/qhexedit2/qhexedit2.spec?expand=1) ~line 114 - "#Install Icon"). Other distributions have no "Icon=[image]" in their desktop entry.

For the sake of distribution, where installing the example GUI is wanted by the user, is it possible to have 16, 24, 32, 48 px^2 png's as part of source? Even an SVG as part of tree would be useful.

**Comment by Simsys** [comment]
fixed, see bad8942ac4fe6f9a6a7a8a4512a4b3a3796494e4
