### ISSUE TITLE
QHexEdit does not forward key press events

### ISSUE THREAD

**Issue by vpiscitello** [Simsys/qhexedit2#117]
When using QHexEdit within a QDialog it should be expected that the functionality of the parent widget is maintained. For example, if a user presses escape, per the Qt documentation, this should close the dialog. However, in looking at the source code of QHexEdit::keyPressEvent, it appears that it does not forward the event to the base class. This results in the default functionality of various key presses, such as escape, to not be handled. 

This could be fixed by adding the following code at the end of QHexEdit::keyPressEvent (line 799 in QHexEdit.cpp)
`QAbstractScrollArea::keyPressEvent(event);`

**Comment by Simsys** [comment]
fixed, see 19eeead4979c1acea8fc871ba6f601d32a3083b2
