### ISSUE TITLE
Undo stack memory leak

### ISSUE THREAD

**Issue by vpreatoni** [Simsys/qhexedit2#119]
My app makes heavy use of replace() function:

`ui->hexWidget->replace(addr, byte);`

With heavy use I mean thousands of writes per second. After a minute of running the app, it takes all system memory, trashing system...

replace() function calls UndoStack::overwrite() function:

`void UndoStack::overwrite(qint64 pos, char c)`
`{`
`    if ((pos >= 0) && (pos < _chunks->size()))`
`    {`
`        QUndoCommand *cc = new CharCommand(_chunks, CharCommand::overwrite, pos, c);`
`        this->push(cc);`
`    }`
`}`

There is an unlimited undo steps, so clearly QUndoCommand *cc = new .... behaves like a memory leak. There should be a limit on undo steps to fix this.

**Comment by Simsys** [comment]
fixed, see efb693f6300d71a8b052824c9b6983d96d27d6fb
