### ISSUE TITLE
Remove trailing address print when bytes per line is even divisor of size

### ISSUE THREAD

**Issue by christopherpow** [Simsys/qhexedit2#123]
I noticed that when displaying a file of 8KB in size the last line is not address 1ff0 followed by 16 bytes as I expected, but is address 2000 followed by no bytes. Attached is a proposed patch. Also a minor hack to the .pro to get a mac build.

Thanks very much for this project it's much better than what I had achieved with Qscintilla for my binary file editing needs.
[droptrailingaddress.txt](https://github.com/Simsys/qhexedit2/files/5279370/droptrailingaddress.txt)

**Comment by Simsys** [comment]
Please provide a github pull request
