### ISSUE TITLE
Unable to install with SIP v5

### ISSUE THREAD

**Issue by Aleks0010V** [Simsys/qhexedit2#127]
I am Unable to install package with SIP v5. 
sipdistutil was deprecated starting from 5.0 version.
SIP v4 is not available from pip.

<pre><code>PS C:\Users\user> pip install C:\Users\user\Documents\qhexedit2-master\
Processing c:\users\user\documents\qhexedit2-master
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\user\appdata\local\programs\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-req-build-nextmkxi\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-req-build-nextmkxi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\user\AppData\Local\Temp\pip-pip-egg-info-1so46rjr'
         cwd: C:\Users\user\AppData\Local\Temp\pip-req-build-nextmkxi\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-req-build-nextmkxi\setup.py", line 8, in <module>
        import sipdistutils
    ModuleNotFoundError: No module named 'sipdistutils'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.</code></pre>

**Comment by Aleks0010V** [comment]
UPD
I am using Windows 10 and it is possible to install Linux into WSL 2 and run
<pre><code>sudo apt install python3-sip-dev</code></pre>
after that sipdistutils will be available, but it is a kind of workaround

**Comment by Simsys** [comment]
Thanks for the tip. Yes, it is a bit difficult to provide this widget on Windows 10. But this is not a problem of the widget, but one of the whole Qt or PyQt environment. I don't work on Windows so I can't solve this problem well either.
