### ISSUE TITLE
File size constraint

### ISSUE THREAD

**Issue by Zatarita** [Simsys/qhexedit2#131]
Due to QByteArrays function; Some features are effected.
For example selections are limited to ~2gb.

**Comment by Simsys** [comment]
Yes, the observation is correct. The question is whether there is a useful application for marking and working with more than 2 gigabytes of selections with this small tool. That would be a big rebuild and the benefit?

**Comment by Zatarita** [comment]
:c I noticed the issue for a reason. It's ok though I rewrote it myself
