### ISSUE TITLE
Multiple display modes?

### ISSUE THREAD

**Issue by neomissing** [Simsys/qhexedit2#133]
Default support only one byte display, can support 2 bytes display together, or four bytes display together
![2bytes](https://user-images.githubusercontent.com/22003930/112405190-c958c100-8d4c-11eb-9c0b-3708cf7ff8e3.png)
![4bytes](https://user-images.githubusercontent.com/22003930/112405194-c9f15780-8d4c-11eb-8feb-3e4c4e8fca39.png)

**Comment by Simsys** [comment]
Yes, you could do that, of course. Code contributions from the community are welcome. But the question is whether that actually improves the usefulness of this widget. After all, it's supposed to be a simple hex widget that can be used anywhere.
