### ISSUE TITLE
Overlapping symbols in ASCII section

### ISSUE THREAD

**Issue by rtborg** [Simsys/qhexedit2#134]
I am using `QHexEdit` with a custom font, and the letters in the ASCII section are overlapping. I tried setting the font letters spacing to a greater value, however that does not influence the ASCII area and the letters are just hidden below each other. Picture attached - I've circled the letter H, on which I've clicked. It's shown correctly when clicked on; however you can see all the other H letters immediately below the circle being partly hidden.

Is there a setting to rectify that issue?

![image](https://user-images.githubusercontent.com/4630005/117970959-f891b480-b331-11eb-952d-129a934e7af1.png)

**Comment by Simsys** [comment]
Please use a monotype or fixed-width font. The Hexeditor is not designed to use proportional fonts. This would also result in the associated characters not being on top of each other. I do not plan to make any changes in this regard.

**Comment by rtborg** [comment]
Thank you
