### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by redtide** [Simsys/qhexedit2#147]
Hello, I was looking for an hex editor made in Qt and I found this project but realized that was a library, so I built the example and I would like to use/test it to replace the one I have installed.

I would like to add some feature starting from a CMake build script that takes also care of translations, but I'm not sure if this project is still in development to propose a pull request or just fork it and modify/remove some other stuff for my own use.

**Comment by AndreiCherniaev** [comment]
The same question.

**Comment by Simsys** [comment]
I'm still alive, but my focus has shifted. I am no longer actively developing QHexedit. However, I do look at the issues and pull requests from time to time. I definitely want QHexEdit to remain a simple and straightforward solution.

Why do you need CMake to integrate the localisation?

What other ideas do you have?

**Comment by AndreiCherniaev** [comment]
> I'm still alive, but my focus has shifted. I am no longer actively developing QHexedit. However, I do look at the issues and pull requests from time to time. I definitely want QHexEdit to remain a simple and straightforward solution.
> 
> Why do you need CMake to integrate the localisation?
> 
> What other ideas do you have?

Do you plan to transfer project to another person? I think it is a good idea. Your project is in demand, now we are use your project in [IMSProg](https://github.com/bigbigmdm/IMSProg?tab=readme-ov-file#list-of-supported-chips)

**Comment by redtide** [comment]
> Why do you need CMake to integrate the localisation?

I don't need CMake for localization, I want CMake as build system because it's both what I use from some time now and also what Qt is using as preferred choice, the translations is an addition on top of it.

The only idea I had in mind was to develop the example as an every day use application and possibly, if accepted, let LXQt Weblate translators team make the project translations.
You can see the current state [here](https://github.com/qtilities/hexedit).

**Comment by Simsys** [comment]
I like what I see here: https://github.com/qtilities/hexedit. The only thing I miss is the Python connection. I think that's a shame, even though I realise that if it's there, it has to be up to date and work.

I am prepared to accept a second admin on the repository. Would you be interested?

**Comment by redtide** [comment]
> I like what I see here: https://github.com/qtilities/hexedit.

Glad you like it!

> The only thing I miss is the Python connection. I think that's a shame, even though I realise that if it's there, it has to be up to date and work.

I had to remove it because I know about nothing on Python bindings and being a fork I decided to not maintain it, though if possible could be restored later at some point, it's still in the git history; I like Python and I use it on other projects of mine.

> I am prepared to accept a second admin on the repository. Would you be interested?

I really appreciate the offer, thank you! Though TBH I'm not sure if to remove the fork from my organization at this point.
I guess you should transfer it to an organization account to add members/maintainers/admins.
If you do, would you mind to a name change like I did? From my POV the Q prefix is about Qt owned classes, the 2... was there a HexEdit1? The organization name would be considered like a name space.

**Comment by Simsys** [comment]
You do not need to remove HexEdit from your account.

I don't quite understand what you are suggesting. Why should I transfer the repository to someone else? I can also grant additional access rights on my account.

About the name: It may be that the choice of name is somewhat unfortunate. There was already a project called QHexEdit at the time ([probably this one](https://github.com/parallaxinc/QHexEdit)), hence the name of the project QHexEdit2. This name is now well known on the net, so I don't think it makes sense to rename it. It is more confusing than useful.

**Comment by redtide** [comment]
> I don't quite understand what you are suggesting. Why should I transfer the repository to someone else? I can also grant additional access rights on my account.

I suggest to you to create an organization account, not of someone else, for the project. GitHub has 2 account types for this reason, to have more users collaborating on the same project, a user account is not meant to be used that way.

Closing, as it was already replied.

**Comment by redtide** [comment]
To be clear I'm not against collaborating in an user account, just feel strange to me, like working in someone else home instead a shared office.

**Comment by Simsys** [comment]
Thanks for the info. I'll have a look, but it will take a few days as I'm travelling.

**Comment by redtide** [comment]
About Python bindings: I'm collaborating on a Python project and started to learn PySide6, which seems to be the official Python bindings by Qt. I see you had bindings for pyQt4 and 5. At this point I would start from scratch with PySide6 and its binding library, [Shiboken6](https://doc.qt.io/qtforpython-6/shiboken6/).
