### ISSUE TITLE
Please bump library version when ABI changes

### ISSUE THREAD

**Issue by manisandro** [Simsys/qhexedit2#17]
Please bump the library version (see [1]) when the ABI changes, as it did between 0.6.6 and 0.7.0, see [2], which was produced with `abi_compliance_checker`.

[1] http://doc.qt.io/qt-4.8/qmake-variable-reference.html#version
[2] https://smani.fedorapeople.org/tmp/compat_report.html

**Comment by Simsys** [comment]
see v0.7.1

**Comment by manisandro** [comment]
Thanks, but you'll want 2.0.0 rather than 1.1.0: the first digit (major) signals ABI incompatible changes, the second one (minor) signals that the interface was extended (i.e. symbols added).

So if you only add new symbols, you just increment the minor digit. If you change or remove symbols, you reset minor to 0 and bump major.
