### ISSUE TITLE
Editing behaves strange when not all options are set.

### ISSUE THREAD

**Issue by hcw70** [Simsys/qhexedit2#21]
When using the QHexEdit widget without calling:
>    setAddressArea(true);
>   setAsciiArea(true);
>    setHighlighting(true);
>    setOverwriteMode(false);
>    setReadOnly(false);
>    setAddressWidth(8);

the cursor jumps back to the first column sometimes when in inserting mode and pressing "2" several times.

When these functions are called, the behaviour was ok.

It looks like some internal variables are not initialized correctly within the constructor but only if these functions are called.

Tested with QT5.5, Linux Ubuntu 14.04.

**Comment by Simsys** [comment]
I can't reproduce this behavior. Exactly these calls are included in the constructor.

**Comment by hcw70** [comment]
Strangely it does not occur at my side any longer.... Thanks for checking !

Regards Hauke
