### ISSUE TITLE
Definitiion of QHexEdit properties

### ISSUE THREAD

**Issue by hcw70** [Simsys/qhexedit2#22]
It would be great to include the following get/set functions also in the definition of Q_PROPERTY, so they become designable in QT Designer when using the QHexEditor as a QT plugin:

    /*! Switch the address area on or off.
      \param addressArea true (show it), false (hide it).
      */
    void setAddressArea(bool addressArea);

    /*! Set the minimum width of the address area.
      \param addressWidth Width in characters.
      */
    void setAddressWidth(int addressWidth);

    /*! Switch the ascii area on or off.
      \param asciiArea true (show it), false (hide it).
      */
    void setAsciiArea(bool asciiArea);

    /*! Switch the highlighting feature on or of.
      \param mode true (show it), false (hide it).
      */
    void setHighlighting(bool mode);

Kind regards

Hauke

**Comment by Simsys** [comment]
fixed, see https://github.com/Simsys/qhexedit2/commit/5d7a4e6d90cdee97a3fdd1b2f4c1d089a37ac754

thanks for reporting this

**Comment by hcw70** [comment]
Thanks for fixing this! 
Regards Hauke
