### ISSUE TITLE
Definition of property "data" should mention signal "dataChanged"

### ISSUE THREAD

**Issue by hcw70** [Simsys/qhexedit2#23]
Q_PROPERTY(QByteArray data READ data WRITE setData)
should include "NOTIFY dataChanged".

This helps in connecting change notifications to the property via QT MetaObject means.

**Comment by Simsys** [comment]
fixed, see https://github.com/Simsys/qhexedit2/commit/5d7a4e6d90cdee97a3fdd1b2f4c1d089a37ac754

thanks for reporting this

**Comment by hcw70** [comment]
Thanks for fixing this! 
Regards Hauke
