### ISSUE TITLE
C++ keywords "and" "or" etc should be avoided

### ISSUE THREAD

**Issue by hcw70** [Simsys/qhexedit2#24]
gcc accepts these but VC++ does not with default settings.

Enabling these keywords for MSVC 2013 as suggested in http://stackoverflow.com/questions/555505/c-alternative-tokens/555524#555524 fails since then we get compiler errors in winnt.h.

So best option would be to replace these "keywords" with their counterparts "&&" and "||" in the code of QHexEdit.

**Comment by Simsys** [comment]
fixed, see https://github.com/Simsys/qhexedit2/commit/f612dd4a8e7d549a6b9e86c365b49d501342d738

thanks for reporting this

**Comment by hcw70** [comment]
Thanks for fixing this! 
Regards Hauke
