### ISSUE TITLE
LONG_LONG_MAX should not be used

### ISSUE THREAD

**Issue by hcw70** [Simsys/qhexedit2#25]
since pre C99 defined, not compilable under MSVC 2013.
See i.e. https://sourceware.org/bugzilla/show_bug.cgi?id=5461#c1

Use LLONG_MAX from <limits.h> / <climits> instead.

See:
http://www.cplusplus.com/reference/climits/

**Comment by Simsys** [comment]
fixed, see https://github.com/Simsys/qhexedit2/commit/276559ec69a30f3d51265b8a893988dc0c5da3d9

thanks for reporting this
