### ISSUE TITLE
Out of range, when select range at end of file.

### ISSUE THREAD

**Issue by sashatref** [Simsys/qhexedit2#26]
Out of range, when select range at end of file and trying to change value

You must do checking of dataSize, before replacing chars.

![2015-12-14 13 22 35](https://cloud.githubusercontent.com/assets/4179764/11779750/d533b08e-a265-11e5-8d49-85dbe5ba80bf.png)

my fix

[qhexedit.txt](https://github.com/Simsys/qhexedit2/files/61114/qhexedit.txt)

**Comment by Simsys** [comment]
Thank you for reporting this issue

I checked it and found, that this problem appears only, when the mouse is used to select the range. The reasen is, that the "_cursorPos"  can be set behind the last byte, when using the mouse. So I solved the problem somewhere else.

see 77928073acbb8ff659564ee0594b66acb96728f2 and 9f73f17b5f89d006febb80a395c2427a7cba9804
