### ISSUE TITLE
Cursor position after deleting last byte

### ISSUE THREAD

**Issue by MRG95** [Simsys/qhexedit2#28]
First off, thanks so much for coding this. It has saved me a bunch of time and I still couldn't come close to having all the features and documentation of yours :smile: 

I noticed one small bug however. If you place your cursor at the end of the data and press backspace to delete the byte, the cursor moves back 1 spot in front of the new last byte. Happens for both overwrite mode and insert mode.

In the else section of the backspace event handler, I made these changes...

```
else
            {

                _bPosCurrent -= 1;
                if (_overwriteMode)
                {
                    if(dataAt(_bPosCurrent+1, 1) == QByteArray::fromHex("00"))
                        replace(_bPosCurrent, char(0));
                    else
                    {
                        replace(_bPosCurrent+1, char(0));
                        _bPosCurrent+=1;
                    }
                }
                else
                    remove(_bPosCurrent, 1);

                if(_chunks->size() != _bPosCurrent)
                    _bPosCurrent -= 1;
                setCursorPosition(2 * _bPosCurrent);
                resetSelection(2 * _bPosCurrent);
            }
```                                

While it's still not exactly what probably should be done, this seemed to fix it for now.

**Comment by Simsys** [comment]
Thanks for this report. For me, the behaviour for overwrite mode is ok. In insert mode there is the isue you have repported.

see 79f4720038ba5799e6fd937baaf9b9e5fff15392
