### ISSUE TITLE
Link error using sip on VS2015 and Windows 8.1

### ISSUE THREAD

**Issue by bluelukas** [Simsys/qhexedit2#33]
I am newbie to use PyQT5.6 and SIP-4.18, python3.5.(OS is Windows8.1)
I am currently trying to import “QHexEdit” in my python project.
But I cannot import the “QHexEdit” because of linking problem.
I was trying to solve this adding “Additional Library Directories” of VS2015
but not working.

Build process and library path setup screen of was attached.

Build error summary is shown as below lines.

running install
running build
running build_ext
building ‘qhexedit’ extension
--
sipqhexeditcmodule.cpp
--
sipqhexeditQHexEdit.cpp
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Python35\libs /LIBPATH:C:\Python35\PCbuild\amd64 “/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64” “/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64” “/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64” “/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64” “/LIBPATH:C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64” Qt5Core.lib Qt5Gui.lib Qt5Widget.lib qhexedit.lib /EXPORT:PyInit_qhexedit build\temp.win-amd64-3.5\Release\build\temp.win-amd64-3.5\Release\sipqhexeditcmodule.obj build\temp.win-amd64-3.5\Release\build\temp.win-amd64-3.5\Release\sipqhexeditQHexEdit.obj /OUT:build\lib.win-amd64-3.5\qhexedit.cp35-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.5\Release\build\temp.win-amd64-3.5\Release\qhexedit.cp35-win_amd64.lib
LINK : fatal error LNK1181: cannot open input file ‘Qt5Core.lib’
error: command ‘C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe’ failed with exit status 1181

![last_state](https://cloud.githubusercontent.com/assets/15103230/16925100/94c02eb2-4d5d-11e6-8658-94db0cd54f39.jpg)
![libpath](https://cloud.githubusercontent.com/assets/15103230/16925099/949eadc8-4d5d-11e6-877c-baad41646a2b.png)

**Comment by Simsys** [comment]
Hi, I'm sorry, but I do not have a windows 8.1 box running here. Try to fix the error which is shown in the Message "LINK : fatal error LNK1181: cannot open input file ‘Qt5Core.lib’". This means probaly, that your path settings are not ok. Please check
