### ISSUE TITLE
How to Insert some text before hex editing

### ISSUE THREAD

**Issue by hbkvikas** [Simsys/qhexedit2#35]
Thanks for the awesome hex editor, but I have so many messages and those messages have so many bytes. How can I display those many messages and their corresponding bytes in your hex editor.
For Ex:
Msg_1
0000| 12 54 65 48 78 | //Ascii Area
...........................................
Msg_2
0000| 54 65 98 45 87 | //Ascii Area
...........................................

Please help me in this regard.

**Comment by Simsys** [comment]
I'm sorry, but this is out of scope of this project. This feature is not part of a hex edit widget.

I propose to arrange a QLabel together with a QHexEdit widget

**Comment by hbkvikas** [comment]
Thanks for your reply. You have done an awesome job on this. I have already tried that but QLabel is getting overridden into the hex texts. Can you please tell how I will move the hex text to the next line of QLabel. It will really help me a lot.
![to](https://cloud.githubusercontent.com/assets/3878744/18501579/3e1ee1ea-7a6f-11e6-8900-7c1db2e39408.PNG)
