### ISSUE TITLE
How to Insert some text before hex editing

### ISSUE THREAD

**Issue by hbkvikas** [Simsys/qhexedit2#36]
Following previous issue:
Thanks for your reply. You have done an awesome job on this. I have already tried that but QLabel is getting overridden into the hex texts. Can you please tell how I will move the hex text to the next line of QLabel. It will really help me a lot.
![to](https://cloud.githubusercontent.com/assets/3878744/18501670/bfe5be88-7a6f-11e6-9aac-0ad66a7ccf6f.PNG)

**Comment by Simsys** [comment]
Sorry, but this is not a problem of QHexEdit. Please ask somewhere else how to work in general with Qt.
