### ISSUE TITLE
No copyright and licensing statement

### ISSUE THREAD

**Issue by izeilstra** [Simsys/qhexedit2#37]
The inclusion of the GNU LGPL v2.1 in the license.txt file under the src directory suggests that the author or authors wish to make this code available for use under the terms of that license. However, without an explicit statement to that effect, it is not legally permissible for me to use this code under those terms. If the intent is to release this code under the LGPL, please add a statement of copyright and licensing to the library.

**Comment by Simsys** [comment]
fixed, see c31a8b88f10a32fec0cd71e9db1e74ecc9011fc7
