### ISSUE TITLE
why use the vitural void setFont?

### ISSUE THREAD

**Issue by hitvery** [Simsys/qhexedit2#38]
Thanks for you great job. I am learning your code. And why do you use `virtual void setFont(const QFont &font);` defined in `qhexedit.h`? It is really weird for me, I understand that QWidget has a function with the same name, and QAbstractScrollArea derived from QWidget, so you just override it? But why `virtual`?

**Comment by Simsys** [comment]
fixed, see 56dd4328b7d961a1b51ff4ff50af45288cddeafa
