### ISSUE TITLE
Leak memory issue

### ISSUE THREAD

**Issue by hmdat** [Simsys/qhexedit2#39]
Hi,
I want to say thank you for great job, for save my time :), this is widget I need
I just use your source in my project and when debug I discover one leak memory issue

QHexEdit::QHexEdit(QWidget *parent) : QAbstractScrollArea(parent)
{
  .....
	_chunks = new Chunks();
 ....
}

Chunks::Chunks()
{
    QBuffer *buf = new QBuffer();
  ...
}

I have fixed it and attached here,
Please check

Thank you again for your great job
[fix_mem_leak.zip](https://github.com/Simsys/qhexedit2/files/568287/fix_mem_leak.zip)

**Comment by Simsys** [comment]
fixed, see 6090b61d48613bc5499f45d1cd3a3420066b1efc
