### ISSUE TITLE
Please bump the library version when introducing incompatible API changes

### ISSUE THREAD

**Issue by manisandro** [Simsys/qhexedit2#41]
For packaging downstream in distributions it is important that the library version is updated when the API changes, otherwise dependent packages aren't rebuilt and can misbehave in various ways - even just refuse to start with a segfault.

The latest version 0.8.0 includes incompatible changes. Could you please update the library version accordingly?

**Comment by Simsys** [comment]
Thank you for this advice and I'm sorry for this and the inconvenience caused to you.

I have changed the library version from 2.1.0 to 2.1.1. This seems not to be enough.

Have I to change it to 2.2.0 or to 3.0.0. Hint: this is really a minimal change and I simply lack the imagination  in how this change could break rebuilds.

**Comment by manisandro** [comment]
No worries. A list of which changes are incompatible is described i.e. in chapter 3.6 of [1]. The meaning of the digits X.Y.Z in the library version are:

X: major digit, increment on backwards incompatible ABI release
Y: minor digit, increment on backwards compatible ABI release
Z: release digit, internal changes only - no change to the ABI

The rules for updating are:
- ABI extended but backwards compatible: bump minor
- ABI changed in a backwards incompatible way: bump major, reset minor

To my knowledge there is little use in bumping Z and it can always stay 0.

[1] http://www.tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html

**Comment by Simsys** [comment]
fixed, see fe57db9e04979987f0cc9ac422f56d0a4591b785

**Comment by manisandro** [comment]
Thanks!
