### ISSUE TITLE
Does not link against the dynamic library

### ISSUE THREAD

**Issue by luigino** [Simsys/qhexedit2#42]
At least on linux.
Is it this on purpose?

**Comment by Simsys** [comment]
I'm using ubuntu linux. 

What do you want to do? Can you compile the example in the example directory?

**Comment by luigino** [comment]
I'm referring to the main application. But perhaps I misunderstand the purpose of the library.

**Comment by Simsys** [comment]
I'm closing this issue, because I do not understand what you mean. If necessary, please reopen it and submit an example!

**Comment by luigino** [comment]
All I'm saying is that the output of
`ldd /usr/bin/qhexedit |grep libqhexedit`
is empty.

Is qhexedit statically linked against libqhexedit or is libqhexedit a completely unrelated thing?
