### ISSUE TITLE
glitch on shift pressed and view slided left

### ISSUE THREAD

**Issue by firexx** [Simsys/qhexedit2#50]
i found a some bug in qhexedit. this bug you can see also with your example app in your head commit.
howto reproduce:
1. start ghexedit example application
2. switch in insert mode(thx for your hint)
3. input e.g. 12 34 56 67 89
4. resize window to horizontal scrollbar show in the bottom of window
5. slide scrollbar right (contetn shifted left)
6. click e.g. on last 9 nibble.
7. press shift key once
8. you get you example application like on attached picture
![qhexedit2_glitch](https://cloud.githubusercontent.com/assets/16118459/21309124/41fbbc84-c5dd-11e6-9723-0b323e12fcc2.png)

this works not only on the last position and also with alt and ctrl keys.

i tried to find a bug, but til now without success.

**Comment by Simsys** [comment]
fixed, see 7822677b6632cfceb9ce2cb47fe3a512c8d2e660

**Comment by firexx** [comment]
this helps, but now the effect occurs. now the right digit becomes "bold". i guess the digit has to be erased and then drawing again to avoid "bold" effect. the magnifier helps to see this effect. thx for commit the bugfixes

**Comment by firexx** [comment]
this changes fixes the problem. first clear region, then drawText. (i put this changes in the branch where i implement the ascii editing and will shortly push it and create a big pull request.)
```
   // paint cursor
    if (_blink && !_readOnly && hasFocus())
        painter.fillRect(_cursorRect, this->palette().color(QPalette::WindowText));
	else{
		QRect r(_pxCursorX - pxOfsX, _pxCursorY - _pxCharHeight, _pxCharWidth, _pxCharHeight);
		QColor c(viewport()->palette().color(QPalette::Base));
		painter.fillRect(r, c);
		painter.drawText(_pxCursorX - pxOfsX, _pxCursorY, _hexDataShown.mid(_cursorPosition - _bPosFirst * 2, 1));
      }
```

**Comment by Simsys** [comment]
Thx for your work

But please: make small (minimal!) pull request. Just on thing at on time!

Your pull request has conflicts and can't be merged!

**Comment by firexx** [comment]
On Tue, Dec 20, 2016 at 11:44 AM, Simsys <notifications@github.com> wrote:

> request has conflic


​it can't be automatically merged. because i did some changes where you did
changes also.

the main feature for editable ascii have to be big. and some small changes​
i did on the way. e.g. better traking for mouse click. or eliminated the
"bold" glitch.

​please merge the pull request manually i guess it is only one place where
conflicts happened.​



-- 
Mit freundlichen Grüßen

Andrej Kostrov

**Comment by firexx** [comment]
if you wish i can merge it. github shown so many files conflicted, but i changed only qhexedit.cpp and .h
