### ISSUE TITLE
paste region in overwrite mode at the end of editable region -> assertion triggered in debug mode

### ISSUE THREAD

**Issue by firexx** [Simsys/qhexedit2#54]
reproduce:
1. copy any two bytes (ctrl-c)
2. go to the end of document
3. paste the clipboard (ctrl-v)
4. crash

**Comment by firexx** [comment]
can't reproduce anymore.

**Comment by firexx** [comment]
reopen.
the issue is not crash but assertion triggered in qt 4.6.0
callstack:
 	QtCored4.dll!qt_message_output(QtMsgType msgType, const char * buf) Line 2214	C++
 	QtCored4.dll!qt_message(QtMsgType msgType, const char * msg, char * ap) Line 2272	C++
 	QtCored4.dll!qFatal(const char * msg, ...) Line 2455	C++
 	QtCored4.dll!qt_assert(const char * assertion, const char * file, int line) Line 1989	C++
 	QtCored4.dll!QByteArray::at(int i) Line 388	C++
 	qhexedit.dll!Chunks::dataChanged(__int64 pos) Line 165	C++
 	qhexedit.dll!CharCommand::redo() Line 86	C++
 	QtGuid4.dll!QUndoStack::push(QUndoCommand * cmd) Line 543	C++
 	qhexedit.dll!UndoStack::removeAt(__int64 pos, __int64 len) Line 140	C++
 	qhexedit.dll!UndoStack::overwrite(__int64 pos, int len, const QByteArray & ba) Line 162	C++
 	qhexedit.dll!QHexEdit::replace(__int64 pos, __int64 len, const QByteArray & ba) Line 328	C++
>	qhexedit.dll!QHexEdit::keyPressEvent(QKeyEvent * event) Line 572	C++

so it is not correct function.

**Comment by Simsys** [comment]
fixed, see 0c6efdfca69e2de1f6ef37dba5eee3f8c3c51f2f
