### ISSUE TITLE
German keyboard can't emit key combinations with Alt-Gr

### ISSUE THREAD

**Issue by firexx** [Simsys/qhexedit2#57]
in ascii edit mode and german keyboard can't emit chars like "{", "[", "]", "}" etc. generated together with Alt-Gr key.

keyPressEvent in part of input ascii have to allow modifiers?

**Comment by firexx** [comment]
i found a solution and shortly push the changes to my fork with following pull request.

**Comment by Simsys** [comment]
fixed, see bd834f6decc2e801b7eac380d19f2607864992b2
