### ISSUE TITLE
undo don't remove over copy paste inserted bytes in overwrite mode.

### ISSUE THREAD

**Issue by firexx** [Simsys/qhexedit2#59]
reproduce:
1. mark  and copy some bytes in clipboard
2. go to the end of document
3. insert from clipboard (the data growing)
4. make undo (ctrl+z)
5. the data becomes the old state, but it will be not shorten

**Comment by Simsys** [comment]
I understand, that after step 3, the total length has increased. I consider that as an error. In overwrite mode, the total length should remain stable.

**Comment by Simsys** [comment]
fixed, see 0c6efdfca69e2de1f6ef37dba5eee3f8c3c51f2f
