### ISSUE TITLE
Improve the widget: Plugin for install in QDesigner

### ISSUE THREAD

**Issue by firexx** [Simsys/qhexedit2#69]

**Comment by firexx** [comment]
@Simsys i got the plugin to work on my Windows PC

can you please check a branch QtDesignerPlugin in my git repo.
it looks very nice ;-)
![image](https://cloud.githubusercontent.com/assets/16118459/21847220/fd5d4a40-d7fa-11e6-9b4d-1f78d3ab202b.png)

**Comment by Simsys** [comment]
Hi Andrej,

I agree: it looks very nice. Unfortunately I can't find qhexeditplugin.pro at your fork. Perhaps the easiest way to handle, is to submit another pull request.

Thx
Winfried

**Comment by firexx** [comment]
Look for other Branche qdesignerplugin. I will also create a pull reqest
:)

Am 12.01.2017 7:48 nachm. schrieb "Simsys" <notifications@github.com>:

**Comment by firexx** [comment]
please find the files here
https://github.com/firexx/qhexedit2/tree/QtDesignerPlugin/src
the last one is the .pro ;-)
Pullrequest will i create immediatly

**Comment by Simsys** [comment]
fixed, see c11e738ca43d304fae0525cdb18d7b9c1f4f08f5
