### ISSUE TITLE
GUI Polishing

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Simsys/qhexedit2#7]
```
1. Line 302 "QHexEdit" instead of "SDI"
2. Line 287 Insert Timout 2000
3. Line 283 Set MinimumWidth to 90
```

Original issue reported on code.google.com by `winfried.simon@gmail.com` on 30 Jan 2012 at 3:52

**Comment by Simsys** [comment]
https://github.com/Simsys/qhexedit2/commit/e4014170002242759beb604f8775aff61a025a2a
