### ISSUE TITLE
Open issues in cursor painting

### ISSUE THREAD

**Issue by audetto** [Simsys/qhexedit2#88]
Hi,

I've seen that you have merged https://github.com/Simsys/qhexedit2/pull/87

and closed https://github.com/Simsys/qhexedit2/pull/85

The current code is still not optimal as a few issues addressed in #85 are still open

1) when the cursor blinks and it is in the OFF state there is plain white underneath, while probably one would like to see the character. same if the focus is lost, the cursor is white and the character damaged

2) in read only mode when the cursor is on the line above a very tall character (e.g. c3) the character is damaged as the rect for the (blinking) cursor is too low and not repainted

These issues have been addressed in #85.

**Comment by Simsys** [comment]
Thank you for pointing that out. I have now adapted the paintEvent() method accordingly. I'm not sure if point two of the list above is solved as well.

Please check again 

see d7c2f4cad05599f0e827c227910488f27b3b2328

**Comment by Simsys** [comment]
seems to have settled
