### ISSUE TITLE
setBytesPerLine();

### ISSUE THREAD

**Issue by hoehli** [Simsys/qhexedit2#94]
Hi,

the member function "setBytesPerLine" is just ignoring my input, changing the member variable ("_bytesPerLine") inside the class constructor of QHexEdit is doing the job. 
But calling "setBytesPerLine" affect a change on "_hexCharsInLine".

Can't figure out this behavior.

best höhli

**Comment by Simsys** [comment]
I can't understand the behavior described. There is the possibility to set the bytes per line in the sample program. This works for me.

I also did another test independently. This test also worked.
